spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rajprince031@gmail.com
    password: rsyv xkng qlos fhrs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true