export const dummyProfiles = [
  {
    id: 1,
    username: "princeraj",
    name: "Prince Raj",
    bio: "Java | Spring Boot | React | Building Proxask 🚀",
    followers: 120,
    following: 85,
    profileVisibility: "public", // public | followers | private

    questions: [
      {
        id: 101,
        question: "How to prepare for Spring Boot interviews?",
        askedTo: "Java Developers",
        answered: true,
        archived: false,
        pinned: true,
        visibility: "private",
        likes: 32,
        comments: 5,
        timestamp: "2 days ago",
      },
      {
        id: 102,
        question: "Best roadmap for learning React?",
        askedTo: "Frontend Experts",
        answered: false,
        archived: false,
        pinned: false,
        visibility: "followers",
        likes: 12,
        comments: 2,
        timestamp: "5 days ago",
      },
      {
        id: 103,
        question: "Is career switch after 3 years okay?",
        askedTo: "Career Mentors",
        answered: true,
        archived: true,
        pinned: false,
        visibility: "public",
        likes: 44,
        comments: 8,
        timestamp: "1 week ago",
      },
    ],
  },

  {
    id: 2,
    username: "aman",
    name: "Aman Verma",
    bio: "Frontend Developer | React | UI/UX Enthusiast",
    followers: 340,
    following: 190,
    profileVisibility: "public",

    questions: [
      {
        id: 201,
        question: "What is the best way to master CSS?",
        askedTo: "Frontend Experts",
        answered: true,
        archived: false,
        pinned: false,
        visibility: "public",
        likes: 56,
        comments: 10,
        timestamp: "1 day ago",
      },
      {
        id: 202,
        question: "Is Tailwind better than CSS modules?",
        askedTo: "UI Engineers",
        answered: false,
        archived: false,
        pinned: false,
        visibility: "public",
        likes: 18,
        comments: 3,
        timestamp: "3 days ago",
      },
    ],
  },

  {
    id: 3,
    username: "john",
    name: "John Doe",
    bio: "Career Mentor | Helping people grow 📈",
    followers: 560,
    following: 120,
    profileVisibility: "followers",

    questions: [
      {
        id: 301,
        question: "How to switch careers safely?",
        askedTo: "Career Mentors",
        answered: true,
        archived: false,
        pinned: true,
        visibility: "followers",
        likes: 88,
        comments: 20,
        timestamp: "3 days ago",
      },
    ],
  },
];
